### ISSUE TITLE
Ajouter un lieu

### ISSUE THREAD

**Issue by bahpetit** [Master-DL/projet-ivvq-2017-2018-bfml#10]
US
En tant que PlaceOwner,
Je souhaite ajouter une nouvelle place,
Afin que des utilisateurs puissent consulter ma place.

TA
Etant donné un PlaceOwner,
Quand j'ajoute une nouvelle place,
Alors la place est consultable par les utilisateurs.

**Comment by princemzb** [comment]
On avait pas laissé tomber celle là????
On était parti dans l’optique que les lieux "place", sont des entreprise à part entière (numero de siren et tout), du coup, un utilisateur (ici visiteur) ne peut pas ajouter un lieu, seul le placeOwner le peut!
@kladier  @bahpetit

**Comment by princemzb** [comment]
On avait pas laissé tomber celle là????
On était parti dans l’optique que les lieux "place", sont des entreprise à part entière (numero de siren et tout), du coup, un utilisateur (ici visiteur) ne peut pas ajouter un lieu, seul le placeOwner le peut!
@kladier  @bahpetit 
![bitmoji](https://render.bitstrips.com/v2/cpanel/d8e66e64-ec9c-495f-947e-9bfe52d2523f-702ed980-1e6b-4a23-b1da-c6891c47c646-v1.png?transparent=1&palette=1&width=246)

**Comment by kladier** [comment]
Tout à fait, du coup j'ai modifié l'user story pour que ça soit le placeowner seulement qui puisse ajouter des places

**Comment by princemzb** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/d080f5b6-bdfd-4482-bf01-52b398c8e790-702ed980-1e6b-4a23-b1da-c6891c47c646-v1.png?transparent=1&palette=1&width=246)

**Comment by princemzb** [comment]
Fausse manip on close
