### ISSUE TITLE
classe domain

### ISSUE THREAD

**Issue by bahpetit** [Master-DL/projet-ivvq-2017-2018-bfml#12]
Les classes domaines 
User(email, login, password, nom, prenom, sexe, dateNaissance, List commentaire)
Comment(description, Lieu, User)

**Comment by princemzb** [comment]
Evenement
![bitmoji](https://render.bitstrips.com/v2/cpanel/3c69fa3e-ffdf-4e72-892c-b6d83e1735a6-702ed980-1e6b-4a23-b1da-c6891c47c646-v1.png?transparent=1&palette=1&width=246)
Place
PlaceOwner
Visitor
