### ISSUE TITLE
Add test datas

### ISSUE THREAD

**Issue by kladier** [Master-DL/projet-ivvq-2017-2018-bfml#14]
Add a general class with test datas of the different class.
See InitialisationService class from friendsofmine project

**Comment by princemzb** [comment]
Done!

**Comment by kladier** [comment]
J'ai réouvert cette issue à cause des tests qui font des erreurs (ils se lancent quand même mais y a les erreurs dont je parlais dans la PR). 
+ y faut ajouter des tests du l'initialisation service, on a perdu 10% de couverture de code avec cette PR ^^

**Comment by princemzb** [comment]
@kladier  @bahpetit svp, y a le Commentcontroller qui merde

**Comment by kladier** [comment]
Pas eu le temps et pas sûr de l'avoir d'ici demain soir.
Par contre on peut laisser tomber cette issue si vraiment c'est  trop galère.. D'autres issues restantes sont + prioritaires
