### ISSUE TITLE
Tout les chemins de toutes nos API ne renvoient que du JSON

### ISSUE THREAD

**Issue by kladier** [Master-DL/projet-ivvq-2017-2018-bfml#21]

**Comment by princemzb** [comment]
@kladier la nomenclature de cette issue est chelou![bitmoji](https://render.bitstrips.com/v2/cpanel/6daef78d-7134-458c-8606-98e921b3feb7-702ed980-1e6b-4a23-b1da-c6891c47c646-v1.png?transparent=1&palette=1&width=246)

**Comment by kladier** [comment]
Hmm, tu veux dire quoi par la nomenclature ??
