### ISSUE TITLE
Modification de mon compte utilisateur

### ISSUE THREAD

**Issue by bahpetit** [Master-DL/projet-ivvq-2017-2018-bfml#3]
US
En tant qu'utilisateur
Je souhaite pouvoir modifier les informations de mon compte utilisateur
Afin d'actualiser des informations, d'en ajouter de nouvelles ou d'en supprimer

TA
Etant donné un utilisateur sur la page de modification de mon compte
Quand j’effectue une modification de mes informations
Alors elles sont appliquées et je reçois une notification.

**Comment by kladier** [comment]
@princemzb est-ce qu'on laisse la possibilité de changer son login et.ou email ?

**Comment by princemzb** [comment]
@kladier oui,
après si ça te complique la tache, f*ck!
