### ISSUE TITLE
Ajouter des filtres aux objets "Place"

### ISSUE THREAD

**Issue by princemzb** [Master-DL/projet-ivvq-2017-2018-bfml#37]
On rajoute une liste "filtres" aux objets place, de manière à permettre aux:
1.placeOwner de les enrichir à volonté;
2. visitor d'y appliquer un critère de trie.

**Comment by kladier** [comment]
Ca serait quoi ces filtres ? Des genres de tag que tu mets sur les places par exemple "Convient aux enfants" ?

**Comment by princemzb** [comment]
Exactement,
y aura une liste figée de filtre. 
De cette liste, le place owner pourra choisir, celles qui correspondent à sa "place".
Il peut en rajouter ou en supprimer à volonté (dans les limites de ce que la liste de filtre propose)!

**Comment by princemzb** [comment]
De même, le visitor devra avoir une liste de filtre qui correspond à celle fourni aux placeOwner, il appliquera ces filtres pour discriminer les places!
